# Generated by Django 5.0.6 on 2025-08-23 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('hourly_rate_eur_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TimeSessionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_allocated', models.IntegerField(blank=True, null=True)),
                ('percent_allocated', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('time_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.timesession')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.workitem')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('van', 'Furgone'), ('truck', 'Camion'), ('car', 'Auto'), ('pickup', 'Pickup'), ('other', 'Altro')], default='van', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Disponibile'), ('in_use', 'In uso'), ('maintenance', 'Manutenzione'), ('unavailable', 'Non disponibile')], default='available', max_length=20)),
                ('odometer_km', models.IntegerField(default=0)),
                ('fuel_level_percent', models.IntegerField(default=100)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['plate'],
                'indexes': [models.Index(fields=['status'], name='core_vehicl_status_187554_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_odometer_km', models.IntegerField()),
                ('end_odometer_km', models.IntegerField(blank=True, null=True)),
                ('start_fuel_percent', models.IntegerField()),
                ('end_fuel_percent', models.IntegerField(blank=True, null=True)),
                ('notes_out', models.TextField(blank=True, null=True)),
                ('notes_in', models.TextField(blank=True, null=True)),
                ('damages_report', models.TextField(blank=True, null=True)),
                ('photos_urls', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_sessions', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.vehicle')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to='core.project')),
                ('time_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.timesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_photos', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.workitem')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('fattura', 'Fattura'), ('scontrino', 'Scontrino'), ('ddt', 'DDT'), ('altro', 'Altro')], default='fattura', max_length=20)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('with_vat', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'In attesa'), ('approved', 'Approvato'), ('rejected', 'Respinto')], default='pending', max_length=20)),
                ('doc_url', models.URLField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cost_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_documents', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_documents', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_documents', to='core.workitem')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['project'], name='core_costdo_project_71e2d4_idx'), models.Index(fields=['status'], name='core_costdo_status_ffab01_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='timesession',
            index=models.Index(fields=['user'], name='core_timese_user_id_96167c_idx'),
        ),
        migrations.AddIndex(
            model_name='timesession',
            index=models.Index(fields=['project'], name='core_timese_project_4af31c_idx'),
        ),
        migrations.AddIndex(
            model_name='timesessionallocation',
            index=models.Index(fields=['time_session'], name='core_timese_time_se_f9ab46_idx'),
        ),
        migrations.AddIndex(
            model_name='timesessionallocation',
            index=models.Index(fields=['work_item'], name='core_timese_work_it_1e0088_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclesession',
            index=models.Index(fields=['vehicle'], name='core_vehicl_vehicle_b37371_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclesession',
            index=models.Index(fields=['user'], name='core_vehicl_user_id_bf6a39_idx'),
        ),
    ]
