# Generated by Django 5.0.6 on 2025-08-23 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timesession_timesessionallocation_vehicle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField()),
                ('category', models.CharField(choices=[('payslip', 'Busta paga'), ('contract', 'Contratto'), ('circular', 'Circolare'), ('other', 'Altro')], default='other', max_length=30)),
                ('requires_ack', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('ack_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='timesession',
            name='core_timese_user_id_96167c_idx',
        ),
        migrations.RemoveIndex(
            model_name='timesession',
            name='core_timese_project_4af31c_idx',
        ),
        migrations.AlterField(
            model_name='workitem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='broadcastdoc',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfolder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.userfolder'),
        ),
        migrations.AddField(
            model_name='userfile',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.userfolder'),
        ),
        migrations.AddIndex(
            model_name='userfolder',
            index=models.Index(fields=['owner'], name='core_userfo_owner_i_824c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='userfolder',
            index=models.Index(fields=['parent'], name='core_userfo_parent__812bec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfolder',
            unique_together={('owner', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['owner'], name='core_userfi_owner_i_a99077_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['folder'], name='core_userfi_folder__70a2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='userfile',
            index=models.Index(fields=['category'], name='core_userfi_categor_4c8096_idx'),
        ),
    ]
